### PR TITLE
Add Prefer and Preference-Applied headers(rfc7240)

### PR DESCRIPTION
**Pull request by steve-chavez**
Adding HTTP headers from https://tools.ietf.org/html/rfc7240.

Also want to take this chance to request you a new release on Hackage.

### CODE REVIEW

**Comment by steve-chavez** [comment]
Polite nudge for you to review this. Also I could help with uploading to hackage if you give me(http://hackage.haskell.org/user/steve_chavez) access.

**Comment by aristidb** [comment]
The code change itself looks fine, but RFC 7240 is only a "Proposed Standard". If this is a really widely used header, we could add it, but otherwise I think it's fine if applications that care about "Prefer" just define the constant themselves.

Can you please point me to examples of where this header is currently used in the wild, because a quick Google doesn't really show anything too useful (other than copies of the IETF document).

**Comment by steve-chavez** [comment]
I think Prefer it's widely used, a quick search for github open issues https://github.com/search?utf8=%E2%9C%93&q=%22Prefer%3A+return%3Drepresentation%22+is%3Aopen&ref=simplesearch.

**Comment by steve-chavez** [comment]
Also in code https://github.com/search?q=%22Prefer%3A+return%3Drepresentation%22+in%3Acode&type=Code

**Comment by aristidb** [comment]
I just released http-types 0.12.2 with this change.

**Pull request merged**
